CRITICAL - 2024-11-23 16:54:32 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 219.
 1 SYSTEMPATH\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-11-23 16:55:26 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 219.
 1 SYSTEMPATH\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2024-11-23 09:57:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:57:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 09:58:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:58:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 09:58:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:58:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 09:58:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:58:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 09:58:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:58:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 09:58:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:58:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 09:58:50 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:58:50 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 09:58:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 09:58:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 10:11:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 10:11:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 10:11:54 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 10:11:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 10:12:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 10:12:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 10:12:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 10:12:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 10:12:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 10:12:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 10:12:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 10:12:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2024-11-23 21:13:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'test-crud', 3306, '', 0)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#4 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#5 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#6 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#9 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\htdocs\ci4-rest\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\htdocs\ci4-rest\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\htdocs\ci4-rest\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `persona...', Array, false)
#3 C:\htdocs\ci4-rest\system\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
#4 C:\htdocs\ci4-rest\app\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', Array)
#5 C:\htdocs\ci4-rest\app\Controllers\Personas.php(16): App\Models\PersonaModel->all()
#6 C:\htdocs\ci4-rest\system\CodeIgniter.php(898): App\Controllers\Personas->index()
#7 C:\htdocs\ci4-rest\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
#8 C:\htdocs\ci4-rest\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\htdocs\ci4-rest\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-11-23 21:13:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `personas`.*, `generos`.`nombre` as `genero`
FROM `personas`
JOIN `generos` ON `generos`.`id` = `personas`.`genero_id`', [], false)
 3 SYSTEMPATH\Model.php(771): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\PersonaModel.php(16): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Personas.php(16): App\Models\PersonaModel->all()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Personas->index()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personas))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
